apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-prod01
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default
  sources:
    - repoURL: https://github.com/ansilh/argocd-lab.git
      targetRevision: main
      path: charts/web-app # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.
      helm:
        parameters:
        - name: "service.type"
          value: "LoadBalancer"

  # Destination cluster and namespace to deploy the application
  destination:
    # cluster API URL
    server: https://192.168.56.59:6443
    # or cluster name
    #name: prod01
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: web-apps

  # Extra information to show in the Argo CD Application details tab
  info:
    - name: 'Web App'
      value: 'https://webapp.com'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

