apiVersion: v2
name: kyverno
description: A Helm chart for deploying Kyverno core components and crd's
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kyverno
    version: 3.1.4
    repository: https://kyverno.github.io/kyverno/
